### ISSUE TITLE
pick_ik not found in loaded plugin descriptions

### ISSUE THREAD

**Issue by philip-n** [PickNikRobotics/pick_ik#32]
First, thanks for creating this solver! It sounds like it matches very well with what I'm looking for and I'm looking forward to test it!

I just cloned the repository and compiled via `colcon build --mixin release`. According to colcon, this works just fine: `Finished <<< pick_ik [57.7s]`. I then sourced the `install/setup.bash`. `ros2 pkg list` now lists `pick_ik` as expected.

To kickstart things, I copied the example from the [USAGE.md]
\(https://github.com/PickNikRobotics/pick_ik/blob/main/doc/USAGE.md). My current `kinematics.yaml` looks like this:

```yaml
/**:
  ros__parameters:
    robot_description_kinematics:
      ur_manipulator:
        # kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
        # kinematics_solver_search_resolution: 0.005
        # kinematics_solver_timeout: 0.005
        # kinematics_solver_attempts: 3
        kinematics_solver: pick_ik/PickIkPlugin
        kinematics_solver_timeout: 0.5
        kinematics_solver_attempts: 3
        mode: local
        rotation_scale: 0.5
        position_threshold: 0.001
        orientation_threshold: 0.01
        cost_threshold: 0.001
        minimal_displacement_weight: 0.0
        gd_step_size: 0.0001
```

However, when launching this via `ros2 launch ur_moveit_config ur_moveit.launch.py ur_type:=ur10e launch_rviz:=true use_fake_hardware:=true`, I get the following error:

```
[move_group-1] [ERROR] [1676915114.700383194] [kinematics_plugin_loader]: The kinematics plugin (ur_manipulator) failed to load. Error: According to the loaded plugin descriptions the class pick_ik/PickIkPlugin with base class type kinematics::KinematicsBase does not exist. Declared types are  cached_ik_kinematics_plugin/CachedKDLKinematicsPlugin cached_ik_kinematics_plugin/CachedSrvKinematicsPlugin kdl_kinematics_plugin/KDLKinematicsPlugin lma_kinematics_plugin/LMAKinematicsPlugin srv_kinematics_plugin/SrvKinematicsPlugin
[move_group-1] [ERROR] [1676915114.700481005] [moveit_ros.robot_model_loader]: Kinematics solver could not be instantiated for joint group ur_manipulator.
```

*(this is actually reported twice, once for the `move_group` and once for `rviz`)*.

Unfortunately, I'm not really familiar with ROS2 yet, so I don't know where / how to start troubleshooting. I'm using ROS Humble, so the `rospack plugin ...` command that is referred to in some older tutorials is not available (and I'm not sure if it would be helpful).

Any ideas and suggestions on what causes this and how to solve it would be much appreciated!
