### ISSUE TITLE
pick_ik not working with newest humble-source docker image

### ISSUE THREAD

**Issue by Zarnack** [PickNikRobotics/pick_ik#38]
Today I updated my humble-source docker image of moveit2 to the newest build. Since then the pick-ik solver is not working properly anymore:

- Manually moving the robot in rviz via the drag and drop orb of the TCP results in no movement of the goal state.
- The robot hand (franka emika panda arm) is always colored light red (not the dark "collision" red)
- Changing the kinematics solver back to `kdl_kinematics_plugin/KDLKinematicsPlugin` or reverting to the old docker moveit2 image (from around 2 months ago) fixes the issue. 
- There are no errors or warnings regarding pick-ik in the startup logs. 

It looks like it is initialized successfully but then cannot produce any valid solution for desired (valid) goal states. 
I installed pick-ik via the released apt package.

My current kinematics.yaml is:
```yaml
panda_arm:
  kinematics_solver: pick_ik/PickIkPlugin
  #kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_timeout: 0.05
  kinematics_solver_attempts: 3
  mode: global
  rotation_scale: 0.5
  position_threshold: 0.001
  orientation_threshold: 0.01
  cost_threshold: 0.001
  minimal_displacement_weight: 0.0
  gd_step_size: 0.0001
```

The rviz panel, moving the orb does not result in a new/moved goal state.
![Screenshot from 2023-03-27 21-43-04](https://user-images.githubusercontent.com/56802851/228049655-a4a92570-4681-4716-bb1c-4160136aba2d.png)
